### ISSUE TITLE
PEOPLE: complete_finance Permission für IT-Support/Leitung fü

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_die_mitte#219]
complete_finance Permission für IT-Support/Leitung auf Bundesebene führt zu n+1 Queries beim Auflisten von Personen. 
Verursacht wird das ganze durch das überarbeitete DropDown 'Rechnung erstellen'. In diesem Dropdown werden sämtliche Layer/Gruppen mit Rechnungseinstellungen aufgelistet. Die Liste ist bei Die Mitte Prod entsprechend lang:

![image](https://user-images.githubusercontent.com/655627/235935640-daeb4770-945d-43e4-98e0-68054bce3b32.png)

Requests dauern dadurch sehr lange. (+30s) Ausserdem ist es auch extrem unpraktisch eine so lange Liste im Dropdown zu haben. (tausende von Pixel lang)

Als Quickfix haben wir die :complete_finance Permission entfernt.

# Tech-Spec

```
/de/groups/22/people?returning=true
eager loading detected
Group::Kanton => [:invoice_config]
Add to your query: .includes([:invoice_config])
ll stack
/usr/src/app/hitobito/app/helpers/dropdown/invoice_new.rb:99:in `block in finance_groups_items'
/usr/src/app/hitobito/app/helpers/dropdown/invoice_new.rb:98:in `map'
/usr/src/app/hitobito/app/helpers/dropdown/invoice_new.rb:98:in `finance_groups_items'
/usr/src/app/hitobito/app/helpers/dropdown/invoice_new.rb:89:in `init_items'
/usr/src/app/hitobito/app/helpers/dropdown/invoice_new.rb:20:in `initialize'
```

- https://github.com/hitobito/hitobito

**Comment by mtnstar** [comment]
n+1 query fix implementiert und in master gemerged: https://github.com/hitobito/hitobito/pull/2100
